### ISSUE TITLE
Req: Enhance exclude documentation

### ISSUE THREAD

**Issue by swizca** [apsislabs/jekyll-tidy#1]
Could the readme file be enhanced surrounding documenting the exclude option?

e.g.
jekyll_tidy: { exclude: [*] }?
jekyll_tidy: { exclude: all }?
jekyll_tidy: { exclude: [ "index.html" "vs" "*/index.html" "/subdir/index.html" "*/subdir/index.html" ] }?

In trying to debug my results, I am finding it handy to turn off jekyll_tidy some of the time in some cases, particularly when in development / locally. Currently I am having to turn off and comment out jekyll_tidy entirely.

I have also found that jekyll \<command> --config config1,config2 fails, if config1 enables an option and config2 disables it, the option remains enabled. It seems that the first option setting sets things and is not overrideable. e.g. --config _config-base.yml,_config-dev.yml.

The readme noting any issues in these regards would be useful.

I have had to revert to a script that does `cat _config-base.yml _config-dev.yml > _config.yml` beforehand. This has worked fine for jekyll_tidy: { compress_html: true }, jekyll_tidy: { compress_html: false }, however, not so for exclude: - thus this request.

Thanks for listening.

**Comment by ncallaway** [comment]
I'm splitting this into two issues. One for the README documentation, and one for the `ignore_env` feature request. The `ignore_env` issue is now https://github.com/apsislabs/jekyll-tidy/issues/3

**Comment by ncallaway** [comment]
I also created a new issue for better handling of exclude options (including globs). Such support would allow you to implement something like:

`jekyll_tidy: { exclude: all }` as `jekyll_tidy: { exclude: [*] }`

**Comment by wkirby** [comment]
@swizca We just pushed a `v0.2.0` of the gem, which should support all the issues you've identified. Thanks!
