### ISSUE TITLE
Support for Ruby<2.3 broken

### ISSUE THREAD

**Issue by abeMedia** [apsislabs/jekyll-tidy#8]
Since the `dig` function used in `/lib/jekyll/tidy.rb` was introduced in Ruby 2.3, support for older Ruby versions is broken and produces the following error message

```sh
path/to/ruby/2.2.0/gems/jekyll-tidy-0.2.0/lib/jekyll/tidy.rb:35:in `ignore_env?': undefined method `dig' for #<Jekyll::Configuration:0x000000024e3750> (NoMethodError)
```

**Comment by wkirby** [comment]
@abeMedia We're now testing for support back to Ruby 2.0.0

**Comment by abeMedia** [comment]
Awesome response time, thanks!
